name: performing cd-icici

on:
  push:
    branches:
      - main

  workflow_dispatch:
         inputs:
             custombranch:
                 description: 'enter the branch'
                 required: true
                 default: 'main'
env:
    RESOURCE_GROUP: "icicisonarrq"
    CLUSTER_NAME:   "Activex-Ipru"
    AZURE_CONTAINER_REGISTRY: "icicihelmreg.azurecr.io"
    USER_NAME: "icicihelmreg"
    VERSION: 1.0.0

jobs:
    deployjob:
      permissions:
        contents: read
        id-token: write
      runs-on: ubuntu-latest
      steps:
          - name: checkout the code
            uses: actions/checkout@v3
            #azure login
          - name: Azure login 
            uses: azure/login@v1
            with:
                creds: ${{secrets.AZURE_CREDS}}

          -  name: Set up kubelogin for non-interactive login
             uses: azure/use-kubelogin@v1
             with:
                kubelogin-version: 'v0.0.25'      
        
          # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
          - name: Get K8s context
            uses: azure/aks-set-context@v3
            with:
              resource-group: ${{ env.RESOURCE_GROUP }}
              cluster-name: ${{ env.CLUSTER_NAME }}
              admin: 'false'
              use-kubelogin: 'true'
          
          - name: Helm deployment
            uses: azure/k8s-bake@v2
            with:
              renderEngine: "helm"
              helmChart: './Ipru/'
              helm-version: "latest"
            id: bake

          - name: Azure docker login
            uses: azure/docker-login@v1
            with:
                  login-server: ${{secrets.LOGIN_SERVER}}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

          - name: Deploys application
            uses: Azure/k8s-deploy@dd4bbd13a5abd2fc9ca8bdcb8aee152bb718fa78
            with:
              manifests: ${{ steps.bake.outputs.manifestsBundle }}
              images: |
                ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.USER_NAME }}:${{ env.VERSION }}
              #imagepullsecrets: |
              # {{ env.PROJECT_NAME }}